/* Generated By:JavaCC: Do not edit this line. AnalizadorConstants.java */

/** 
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface AnalizadorConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int BICONDICIONAL = 1;
  /** RegularExpression Id. */
  int CONDICIONAL = 2;
  /** RegularExpression Id. */
  int DISYUNCION = 3;
  /** RegularExpression Id. */
  int CONJUNCION = 4;
  /** RegularExpression Id. */
  int NEGACION = 5;
  /** RegularExpression Id. */
  int VARIABLE = 6;
  /** RegularExpression Id. */
  int PARENTESIS_IZQ = 7;
  /** RegularExpression Id. */
  int PARENTESIS_DER = 8;
  /** RegularExpression Id. */
  int CORCHETE_IZQ = 9;
  /** RegularExpression Id. */
  int CORCHETE_DER = 10;
  /** RegularExpression Id. */
  int LLAVE_IZQ = 11;
  /** RegularExpression Id. */
  int LLAVE_DER = 12;
  /** RegularExpression Id. */
  int FORMULAVALIDA = 18;
  /** RegularExpression Id. */
  int CONTRADICCION = 19;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\"=\"",
    "\">\"",
    "\"|\"",
    "\"&\"",
    "\"\\u00ac\"",
    "<VARIABLE>",
    "\"(\"",
    "\")\"",
    "\"[\"",
    "\"]\"",
    "\"{\"",
    "\"}\"",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\r\\n\"",
    "\"1\"",
    "\"0\"",
  };

}
