/* Generated By:JavaCC: Do not edit this line. Analizador.java */
public class Analizador implements AnalizadorConstants {

    public static void main(String[] args){
        Analizador analizador = new Analizador(System.in);

        try{
            System.out.println("Iniciando an\u00e1lisis...\n");
            analizador.inicializarArbol();

            System.out.println("An\u00e1lisis finalizado");
        }catch(ParseException e){
            System.out.println("Error de sintaxis: " + e.getMessage());
        }
    }

    class Nodo {
        Token token;
        Nodo izquierdo, derecho, padre;

        public Nodo(Token token){
            this.token = token;
            this.izquierdo = null;
            this.derecho = null;
            this.padre = null;
        }
    }

    class Arbol{
        Nodo raiz;

        public Arbol(){
            raiz = null;
        }

        public Arbol(Nodo raiz){
            this.raiz = raiz;
        }

        void enOrden(){
            System.out.println("\nRecorrido in-orden: ");
            enOrdenRec(raiz);
            System.out.println("\n");
        }

        void enOrdenRec(Nodo raiz){
            if (raiz != null) {
                //System.out.print(raiz.token.image + " ");
                enOrdenRec(raiz.izquierdo);
                //System.out.println("cambio");
                System.out.print(raiz.token.image + " ");
                /*if(raiz.padre!=null){
                    System.out.println("Padre: "+raiz.padre.token.image + " ");
                }else{
                    System.out.println("Padre null");
                }
                
                System.out.println("Raiz: "+raiz.token.image + " ");*/
                enOrdenRec(raiz.derecho);
            }
        }

        public void insertar(Arbol arbolIzq, Arbol arbolDer, Nodo operador){
            operador.izquierdo = arbolIzq.raiz;
            operador.derecho = arbolDer.raiz;
            operador.izquierdo.padre = operador;
            operador.derecho.padre = operador;
            this.raiz = operador;
        }

        public Nodo getRaiz(){
            return raiz;
        }

        public void setRaiz(Nodo raiz){
            this.raiz = raiz;
        }
    }

    class ConversionFNC{
        Arbol arbol;
        boolean detectaCambios;

        public ConversionFNC(Arbol arbol){
            this.arbol = arbol;
        }

        Nodo obtenerSubArbol(Nodo raiz){
            if (raiz == null) {
                return null;
            }

            Nodo nuevoNodo = new Nodo(new Token(raiz.token.kind,raiz.token.image));
            //nuevoNodo.padre = raiz.padre;
            //System.out.println("nvo nodo: "+nuevoNodo.token.image);
            nuevoNodo.izquierdo = obtenerSubArbol(raiz.izquierdo);
            if(nuevoNodo.izquierdo != null){
                nuevoNodo.izquierdo.padre = nuevoNodo;
            }

            nuevoNodo.derecho = obtenerSubArbol(raiz.derecho);
            if(nuevoNodo.derecho != null){
                nuevoNodo.derecho.padre = nuevoNodo;
            }

            return nuevoNodo;
        }

        void generarFNC(){
            detectaCambios = false;

            System.out.println("Generar FNC");
            do{
                System.out.println("ITERACION");
                detectaCambios = false;
                aplicarConversion(this.arbol.raiz);
            }while(detectaCambios);

            System.out.println();
        }

        void aplicarConversion(Nodo raiz){
            if (raiz != null) {
                if(!detectaCambios){
                    aplicarConversion(raiz.izquierdo);
                    if(!detectaCambios){
                        aplicarSustituciones(raiz);
                    }
                    aplicarConversion(raiz.derecho);
                }
            }
        }

        void aplicarSustituciones(Nodo raiz){

            if(raiz.token.kind == BICONDICIONAL){
                sustituyeBicondicional(raiz);
                detectaCambios = true;
            }else if(raiz.token.kind == CONDICIONAL){
                sustituyeCondicional(raiz);
                detectaCambios = true;
            }else if(raiz.token.kind == NEGACION){
                if(raiz.derecho.token.kind == NEGACION){
                    eliminarDobleNegacion(raiz);
                    detectaCambios = true;
                }else{
                    detectaCambios = false;
                }
            }else{
                //detectaCambios = false;
            }

            if(raiz.token.kind == NEGACION){
                if(raiz.derecho.token.kind == CONJUNCION || raiz.derecho.token.kind == DISYUNCION){
                    leyDeMorgan(raiz);
                    detectaCambios = true;
                }
            }


            leyDistributiva(raiz);
            leyConmutativa(raiz);
            idempotencia(raiz);
            complementacion(raiz);
        }

        void sustituyeBicondicional(Nodo raiz){
            Nodo nodoIzqA = obtenerSubArbol(raiz.izquierdo);
            nodoIzqA.padre = raiz.izquierdo;
            Nodo nodoDerA = obtenerSubArbol(raiz.derecho);
            nodoDerA.padre = raiz.izquierdo;

            Nodo nodoIzqB = obtenerSubArbol(raiz.izquierdo);
            nodoIzqB.padre = raiz.derecho;
            Nodo nodoDerB = obtenerSubArbol(raiz.derecho);
            nodoDerB.padre = raiz.derecho;

            raiz.token = new Token(CONJUNCION, "&");
            raiz.izquierdo.token = new Token(CONDICIONAL, ">");
            raiz.izquierdo.izquierdo = nodoIzqA;
            raiz.izquierdo.derecho = nodoDerA;

            raiz.derecho.token = new Token(CONDICIONAL, ">");
            raiz.derecho.izquierdo = nodoDerB;
            raiz.derecho.derecho = nodoIzqB;
        }

        void sustituyeCondicional(Nodo raiz){
            Nodo nodoIzq = obtenerSubArbol(raiz.izquierdo);
            nodoIzq.padre = raiz.izquierdo;

            Nodo nodoDer = obtenerSubArbol(raiz.derecho);
            nodoDer.padre = raiz;

            raiz.token = new Token(DISYUNCION, "|");

            raiz.izquierdo.token = new Token(NEGACION, "\u00ac");
            raiz.izquierdo.derecho = nodoIzq;
            raiz.izquierdo.izquierdo = null;

            raiz.derecho = nodoDer;
        }

        void eliminarDobleNegacion(Nodo raiz){
            if(raiz.padre != null){
                if(raiz.padre.izquierdo == raiz){
                    raiz.padre.izquierdo = raiz.derecho.derecho;
                    raiz.derecho.derecho.padre = raiz.padre;
                }else if(raiz.padre.derecho == raiz){
                    raiz.padre.derecho = raiz.derecho.derecho;
                    raiz.derecho.derecho.padre = raiz.padre;
                }
            }else{//En el caso que haya una negación en la raiz del arbol
                this.arbol.raiz = raiz.derecho.derecho;
                this.arbol.raiz.padre = null;
            }
        }

        void leyDeMorgan(Nodo raiz){
            if(raiz.derecho.token.kind == CONJUNCION){
                Nodo nodoIzq = obtenerSubArbol(raiz.derecho.izquierdo);
                Nodo nodoDer = obtenerSubArbol(raiz.derecho.derecho);

                raiz.token = new Token(DISYUNCION, "|");

                raiz.derecho = new Nodo(new Token(NEGACION,"\u00ac"));
                raiz.derecho.derecho = nodoDer;
                raiz.derecho.padre = raiz;
                nodoDer.padre = raiz.derecho;

                raiz.izquierdo = new Nodo(new Token(NEGACION,"\u00ac"));
                raiz.izquierdo.derecho = nodoIzq;
                raiz.izquierdo.padre = raiz;
                nodoIzq.padre = raiz.izquierdo;

            }else if(raiz.derecho.token.kind == DISYUNCION){
                Nodo nodoIzq = obtenerSubArbol(raiz.derecho.izquierdo);
                Nodo nodoDer = obtenerSubArbol(raiz.derecho.derecho);

                raiz.token = new Token(CONJUNCION, "&");

                raiz.derecho = new Nodo(new Token(NEGACION,"\u00ac"));
                raiz.derecho.derecho = nodoDer;
                raiz.derecho.padre = raiz;
                nodoDer.padre = raiz.derecho;

                raiz.izquierdo = new Nodo(new Token(NEGACION,"\u00ac"));
                raiz.izquierdo.derecho = nodoIzq;
                raiz.izquierdo.padre = raiz;
                nodoIzq.padre = raiz.izquierdo;
            }
        }

        void leyDistributiva(Nodo raiz){
            if(raiz.token.kind == DISYUNCION){//Por la derecha
                if(raiz.derecho.token.kind == CONJUNCION && (raiz.izquierdo.token.kind == VARIABLE || raiz.izquierdo.token.kind == NEGACION)){
                    //Evaluación por la derecha (variable sola a la izquierda)
                    Nodo nodoIzqA = obtenerSubArbol(raiz.izquierdo);
                    Nodo nodoIzqB = obtenerSubArbol(raiz.izquierdo);

                    Nodo nodoDerDer = obtenerSubArbol(raiz.derecho.derecho);
                    Nodo nodoDerIzq = obtenerSubArbol(raiz.derecho.izquierdo);

                    raiz.token = new Token(CONJUNCION, "&");

                    raiz.derecho = new Nodo(new Token(DISYUNCION,"|"));
                    raiz.derecho.padre = raiz;
                    raiz.derecho.derecho = nodoDerDer;
                    nodoDerDer.padre = raiz.derecho;

                    raiz.derecho.izquierdo = nodoIzqB;
                    nodoIzqB.padre = raiz.derecho;


                    raiz.izquierdo = new Nodo(new Token(DISYUNCION,"|"));
                    raiz.izquierdo.padre = raiz;
                    raiz.izquierdo.derecho = nodoDerIzq;
                    nodoDerIzq.padre = raiz.izquierdo;

                    raiz.izquierdo.izquierdo = nodoIzqA;
                    nodoIzqA.padre = raiz.izquierdo;
                    detectaCambios = true;
                }else if(raiz.izquierdo.token.kind == CONJUNCION && (raiz.derecho.token.kind == VARIABLE || raiz.derecho.token.kind == NEGACION)){
                    //Evaluación por la izquierda (variable sola a la derecha)
                    Nodo nodoDerA = obtenerSubArbol(raiz.derecho);
                    Nodo nodoDerB = obtenerSubArbol(raiz.derecho);

                    Nodo nodoIzqDer = obtenerSubArbol(raiz.izquierdo.derecho);
                    Nodo nodoIzqIzq = obtenerSubArbol(raiz.izquierdo.izquierdo);

                    raiz.token = new Token(CONJUNCION, "&");

                    raiz.derecho = new Nodo(new Token(DISYUNCION,"|"));
                    raiz.derecho.padre = raiz;
                    raiz.derecho.derecho = nodoDerB;
                    nodoDerB.padre = raiz.derecho;

                    raiz.derecho.izquierdo = nodoIzqDer;
                    nodoIzqDer.padre = raiz.derecho;


                    raiz.izquierdo = new Nodo(new Token(DISYUNCION,"|"));
                    raiz.izquierdo.padre = raiz;
                    raiz.izquierdo.derecho = nodoDerA;
                    nodoDerA.padre = raiz.izquierdo;

                    raiz.izquierdo.izquierdo = nodoIzqIzq;
                    nodoIzqIzq.padre = raiz.izquierdo;
                    detectaCambios = true;
                }

            }else if(raiz.token.kind == CONJUNCION){//Por la derecha
                if(raiz.derecho.token.kind == DISYUNCION && (raiz.izquierdo.token.kind == VARIABLE || raiz.izquierdo.token.kind == NEGACION)){
                    //Evaluación por la derecha (variable sola a la izquierda)
                    Nodo nodoIzqA = obtenerSubArbol(raiz.izquierdo);
                    Nodo nodoIzqB = obtenerSubArbol(raiz.izquierdo);

                    Nodo nodoDerDer = obtenerSubArbol(raiz.derecho.derecho);
                    Nodo nodoDerIzq = obtenerSubArbol(raiz.derecho.izquierdo);

                    raiz.token = new Token(DISYUNCION, "|");

                    raiz.derecho = new Nodo(new Token(CONJUNCION,"&"));
                    raiz.derecho.padre = raiz;
                    raiz.derecho.derecho = nodoDerDer;
                    nodoDerDer.padre = raiz.derecho;

                    raiz.derecho.izquierdo = nodoIzqB;
                    nodoIzqB.padre = raiz.derecho;


                    raiz.izquierdo = new Nodo(new Token(CONJUNCION,"&"));
                    raiz.izquierdo.padre = raiz;
                    raiz.izquierdo.derecho = nodoDerIzq;
                    nodoDerIzq.padre = raiz.izquierdo;

                    raiz.izquierdo.izquierdo = nodoIzqA;
                    nodoIzqA.padre = raiz.izquierdo;
                    detectaCambios = true;
                }else if(raiz.izquierdo.token.kind == DISYUNCION && (raiz.derecho.token.kind == VARIABLE || raiz.derecho.token.kind == NEGACION)){
                    //Evaluación por la izquierda (variable sola a la derecha)
                    Nodo nodoDerA = obtenerSubArbol(raiz.derecho);
                    Nodo nodoDerB = obtenerSubArbol(raiz.derecho);

                    Nodo nodoIzqDer = obtenerSubArbol(raiz.izquierdo.derecho);
                    Nodo nodoIzqIzq = obtenerSubArbol(raiz.izquierdo.izquierdo);

                    raiz.token = new Token(DISYUNCION, "|");

                    raiz.derecho = new Nodo(new Token(CONJUNCION,"&"));
                    raiz.derecho.padre = raiz;
                    raiz.derecho.derecho = nodoDerB;
                    nodoDerB.padre = raiz.derecho;

                    raiz.derecho.izquierdo = nodoIzqDer;
                    nodoIzqDer.padre = raiz.derecho;


                    raiz.izquierdo = new Nodo(new Token(CONJUNCION,"&"));
                    raiz.izquierdo.padre = raiz;
                    raiz.izquierdo.derecho = nodoDerA;
                    nodoDerA.padre = raiz.izquierdo;

                    raiz.izquierdo.izquierdo = nodoIzqIzq;
                    nodoIzqIzq.padre = raiz.izquierdo;
                    detectaCambios = true;
                }
            }
        }


        void leyConmutativa(Nodo raiz){
            boolean detectaConmutacion = false;

            if(raiz.token.kind == DISYUNCION){
                //Verifica que la otra disyunción esté a la izquierda
                if(raiz.izquierdo.token.kind == DISYUNCION){

                    if(raiz.derecho.token.kind == VARIABLE){ //Verifica de lado derecho haya una variable (sola)
                        //Se trata el nodo izquierdo.izquierdo
                        if(raiz.izquierdo.izquierdo.token.kind == VARIABLE && !detectaConmutacion){//Verifica que el nodo IZQUIERDO de la disyunción hija sea una variable

                            if(raiz.derecho.token.image.equals(raiz.izquierdo.izquierdo.token.image)){//Verifica que sean la misma variable
                                Nodo nodoDer = obtenerSubArbol(raiz.derecho);

                                raiz.izquierdo.derecho.padre = raiz;
                                raiz.derecho = raiz.izquierdo.derecho;

                                raiz.izquierdo.derecho = nodoDer;
                                nodoDer.padre = raiz.izquierdo;
                                detectaConmutacion = true;
                            }

                        }else if(raiz.izquierdo.izquierdo.token.kind == NEGACION && !detectaConmutacion){//Verifica que el nodo IZQUIERDO de la disyunción hija sea una negación

                            if(raiz.derecho.token.image.equals(raiz.izquierdo.izquierdo.derecho.token.image)){//Verifica que sean la misma variable
                                Nodo nodoDer = obtenerSubArbol(raiz.derecho);

                                raiz.izquierdo.derecho.padre = raiz;
                                raiz.derecho = raiz.izquierdo.derecho;

                                raiz.izquierdo.derecho = nodoDer;
                                nodoDer.padre = raiz.izquierdo;
                                detectaConmutacion = true;
                            }
                        }

                        //Se trata el nodo izquierdo.derecho
                        if(raiz.izquierdo.derecho.token.kind == VARIABLE && !detectaConmutacion){//Verifica que el nodo DERECHO de la disyunción hija sea una variable

                            if(raiz.derecho.token.image.equals(raiz.izquierdo.derecho.token.image)){//Verifica que sean la misma variable
                                Nodo nodoDer = obtenerSubArbol(raiz.derecho);

                                raiz.izquierdo.izquierdo.padre = raiz;
                                raiz.derecho = raiz.izquierdo.izquierdo;

                                raiz.izquierdo.izquierdo = nodoDer;
                                nodoDer.padre = raiz.izquierdo;
                                detectaConmutacion = true;
                            }

                        }else if(raiz.izquierdo.derecho.token.kind == NEGACION && !detectaConmutacion){//Verifica que el nodo DERECHO de la disyunción hija sea una negación

                            if(raiz.derecho.token.image.equals(raiz.izquierdo.derecho.derecho.token.image)){//Verifica que sean la misma variable
                                Nodo nodoDer = obtenerSubArbol(raiz.derecho);

                                raiz.izquierdo.izquierdo.padre = raiz;
                                raiz.derecho = raiz.izquierdo.izquierdo;

                                raiz.izquierdo.izquierdo = nodoDer;
                                nodoDer.padre = raiz.izquierdo;
                                detectaConmutacion = true;
                            }
                        }

                    }else if(raiz.derecho.token.kind == NEGACION){//Verifica que de lado derecho haya una negación (seguida de una variable)
                        //Se trata el nodo izquierdo.izquierdo
                        if(raiz.izquierdo.izquierdo.token.kind == VARIABLE && !detectaConmutacion){//Verifica que el nodo IZQUIERDO de la disyunción hija sea una variable

                            if(raiz.derecho.derecho.token.image.equals(raiz.izquierdo.izquierdo.token.image)){//Verifica que sean la misma variable
                                Nodo nodoDer = obtenerSubArbol(raiz.derecho);

                                raiz.izquierdo.derecho.padre = raiz;
                                raiz.derecho = raiz.izquierdo.derecho;

                                raiz.izquierdo.derecho = nodoDer;
                                nodoDer.padre = raiz.izquierdo;
                                detectaConmutacion = true;
                            }

                        }else if(raiz.izquierdo.izquierdo.token.kind == NEGACION && !detectaConmutacion){//Verifica que el nodo IZQUIERDO de la disyunción hija sea una negación

                            if(raiz.derecho.derecho.token.image.equals(raiz.izquierdo.izquierdo.derecho.token.image)){//Verifica que sean la misma variable
                                Nodo nodoDer = obtenerSubArbol(raiz.derecho);

                                raiz.izquierdo.derecho.padre = raiz;
                                raiz.derecho = raiz.izquierdo.derecho;

                                raiz.izquierdo.derecho = nodoDer;
                                nodoDer.padre = raiz.izquierdo;
                                detectaConmutacion = true;
                            }

                        }

                        //Se trata el nodo izquierdo.derecho
                        if(raiz.izquierdo.derecho.token.kind == VARIABLE && !detectaConmutacion){//Verifica que el nodo DERECHO de la disyunción hija sea una variable

                            if(raiz.derecho.derecho.token.image.equals(raiz.izquierdo.derecho.token.image)){//Verifica que sean la misma variable
                                Nodo nodoDer = obtenerSubArbol(raiz.derecho);

                                raiz.izquierdo.izquierdo.padre = raiz;
                                raiz.derecho = raiz.izquierdo.izquierdo;

                                raiz.izquierdo.izquierdo = nodoDer;
                                nodoDer.padre = raiz.izquierdo;
                                detectaConmutacion = true;
                            }

                        }else if(raiz.izquierdo.derecho.token.kind == NEGACION && !detectaConmutacion){//Verifica que el nodo DERECHO de la disyunción hija sea una negación

                            if(raiz.derecho.derecho.token.image.equals(raiz.izquierdo.derecho.derecho.token.image)){//Verifica que sean la misma variable
                                Nodo nodoDer = obtenerSubArbol(raiz.derecho);

                                raiz.izquierdo.izquierdo.padre = raiz;
                                raiz.derecho = raiz.izquierdo.izquierdo;

                                raiz.izquierdo.izquierdo = nodoDer;
                                nodoDer.padre = raiz.izquierdo;
                                detectaConmutacion = true;
                            }
                        }
                    }
                }//Fin disyunción a la IZQUIERDA

                //Verifica que la otra disyunción esté a la DERECHA
                if(raiz.derecho.token.kind == DISYUNCION){

                    if(raiz.izquierdo.token.kind == VARIABLE){ //Verifica de lado IZQUIERDO haya una variable (sola)

                        //Se trata que el Nodo raiz.izquierdo == raiz.derecho.izquierdo
                        if(raiz.derecho.izquierdo.token.kind == VARIABLE && !detectaConmutacion){//Verifica que el nodo IZQUIERDO de la disyunción hija sea una variable

                            if(raiz.izquierdo.token.image.equals(raiz.derecho.izquierdo.token.image)){//Verifica que sean la misma variable
                                Nodo nodoIzq = obtenerSubArbol(raiz.izquierdo);

                                raiz.derecho.derecho.padre = raiz;
                                raiz.izquierdo = raiz.derecho.derecho;

                                raiz.derecho.derecho = nodoIzq;
                                nodoIzq.padre = raiz.derecho;
                                detectaConmutacion = true;
                            }

                        }else if(raiz.derecho.izquierdo.token.kind == NEGACION && !detectaConmutacion){//Verifica que el nodo IZQUIERDO de la disyunción hija sea una negación

                            if(raiz.izquierdo.token.image.equals(raiz.derecho.izquierdo.derecho.token.image)){//Verifica que sean la misma variable
                                Nodo nodoIzq = obtenerSubArbol(raiz.izquierdo);

                                raiz.derecho.derecho.padre = raiz;
                                raiz.izquierdo = raiz.derecho.derecho;

                                raiz.derecho.derecho = nodoIzq;
                                nodoIzq.padre = raiz.derecho;
                                detectaConmutacion = true;
                            }
                        }

                        //Se trata que el Nodo raiz.izquierdo == raiz.derecho.derecho
                        if(raiz.derecho.derecho.token.kind == VARIABLE && !detectaConmutacion){//Verifica que el nodo DERECHO de la disyunción hija sea una variable

                            if(raiz.izquierdo.token.image.equals(raiz.derecho.derecho.token.image)){//Verifica que sean la misma variable
                                Nodo nodoIzq = obtenerSubArbol(raiz.izquierdo);

                                raiz.derecho.izquierdo.padre = raiz;
                                raiz.izquierdo = raiz.derecho.izquierdo;

                                raiz.derecho.izquierdo = nodoIzq;
                                nodoIzq.padre = raiz.derecho;
                                detectaConmutacion = true;
                            }
                        }else if(raiz.derecho.derecho.token.kind == NEGACION && !detectaConmutacion){//Verifica que el nodo DERECHO de la disyunción hija sea una negación

                            if(raiz.izquierdo.token.image.equals(raiz.derecho.derecho.derecho.token.image)){//Verifica que sean la misma variable
                                Nodo nodoIzq = obtenerSubArbol(raiz.izquierdo);

                                raiz.derecho.izquierdo.padre = raiz;
                                raiz.izquierdo = raiz.derecho.izquierdo;

                                raiz.derecho.izquierdo = nodoIzq;
                                nodoIzq.padre = raiz.derecho;
                                detectaConmutacion = true;
                            }
                        }


                    }else if(raiz.izquierdo.token.kind == NEGACION){//Verifica que de lado IZQUIERDO haya una negación (seguida de una variable)

                        //Se trata que el Nodo raiz.izquierdo == raiz.derecho.izquierdo
                        if(raiz.derecho.izquierdo.token.kind == VARIABLE && !detectaConmutacion){//Verifica que el nodo IZQUIERDO de la disyunción hija sea una variable

                            if(raiz.izquierdo.derecho.token.image.equals(raiz.derecho.izquierdo.token.image)){//Verifica que sean la misma variable
                                Nodo nodoIzq = obtenerSubArbol(raiz.izquierdo);

                                raiz.derecho.derecho.padre = raiz;
                                raiz.izquierdo = raiz.derecho.derecho;

                                raiz.derecho.derecho = nodoIzq;
                                nodoIzq.padre = raiz.derecho;
                                detectaConmutacion = true;
                            }

                        }else if(raiz.derecho.izquierdo.token.kind == NEGACION && !detectaConmutacion){//Verifica que el nodo IZQUIERDO de la disyunción hija sea una negación

                            if(raiz.izquierdo.derecho.token.image.equals(raiz.derecho.izquierdo.derecho.token.image)){//Verifica que sean la misma variable
                                Nodo nodoIzq = obtenerSubArbol(raiz.izquierdo);

                                raiz.derecho.derecho.padre = raiz;
                                raiz.izquierdo = raiz.derecho.derecho;

                                raiz.derecho.derecho = nodoIzq;
                                nodoIzq.padre = raiz.derecho;
                                detectaConmutacion = true;
                            }
                        }

                        //Se trata que el Nodo raiz.izquierdo == raiz.derecho.derecho
                        if(raiz.derecho.derecho.token.kind == VARIABLE && !detectaConmutacion){//Verifica que el nodo DERECHO de la disyunción hija sea una variable

                            if(raiz.izquierdo.derecho.token.image.equals(raiz.derecho.derecho.token.image)){//Verifica que sean la misma variable
                                Nodo nodoIzq = obtenerSubArbol(raiz.izquierdo);

                                raiz.derecho.izquierdo.padre = raiz;
                                raiz.izquierdo = raiz.derecho.izquierdo;

                                raiz.derecho.izquierdo = nodoIzq;
                                nodoIzq.padre = raiz.derecho;
                                detectaConmutacion = true;
                            }
                        }else if(raiz.derecho.derecho.token.kind == NEGACION && !detectaConmutacion){//Verifica que el nodo DERECHO de la disyunción hija sea una negación

                            if(raiz.izquierdo.derecho.token.image.equals(raiz.derecho.derecho.derecho.token.image)){//Verifica que sean la misma variable
                                Nodo nodoIzq = obtenerSubArbol(raiz.izquierdo);

                                raiz.derecho.izquierdo.padre = raiz;
                                raiz.izquierdo = raiz.derecho.izquierdo;

                                raiz.derecho.izquierdo = nodoIzq;
                                nodoIzq.padre = raiz.derecho;
                                detectaConmutacion = true;
                            }
                        }
                    }
                }//Fin disyunción a la derecha
            }//Fin conmutación de la disyuncioón


            if(raiz.token.kind == CONJUNCION){
                //Verifica que la otra conjunción esté a la izquierda
                if(raiz.izquierdo.token.kind == CONJUNCION){

                    if(raiz.derecho.token.kind == VARIABLE){ //Verifica de lado derecho haya una variable (sola)
                        //Se trata el nodo izquierdo.izquierdo
                        if(raiz.izquierdo.izquierdo.token.kind == VARIABLE && !detectaConmutacion){//Verifica que el nodo IZQUIERDO de la conjunción hija sea una variable

                            if(raiz.derecho.token.image.equals(raiz.izquierdo.izquierdo.token.image)){//Verifica que sean la misma variable
                                Nodo nodoDer = obtenerSubArbol(raiz.derecho);

                                raiz.izquierdo.derecho.padre = raiz;
                                raiz.derecho = raiz.izquierdo.derecho;

                                raiz.izquierdo.derecho = nodoDer;
                                nodoDer.padre = raiz.izquierdo;
                                detectaConmutacion = true;
                            }

                        }else if(raiz.izquierdo.izquierdo.token.kind == NEGACION && !detectaConmutacion){//Verifica que el nodo IZQUIERDO de la conjunción hija sea una negación

                            if(raiz.derecho.token.image.equals(raiz.izquierdo.izquierdo.derecho.token.image)){//Verifica que sean la misma variable
                                Nodo nodoDer = obtenerSubArbol(raiz.derecho);

                                raiz.izquierdo.derecho.padre = raiz;
                                raiz.derecho = raiz.izquierdo.derecho;

                                raiz.izquierdo.derecho = nodoDer;
                                nodoDer.padre = raiz.izquierdo;
                                detectaConmutacion = true;
                            }
                        }

                        //Se trata el nodo izquierdo.derecho
                        if(raiz.izquierdo.derecho.token.kind == VARIABLE && !detectaConmutacion){//Verifica que el nodo DERECHO de la conjunción hija sea una variable

                            if(raiz.derecho.token.image.equals(raiz.izquierdo.derecho.token.image)){//Verifica que sean la misma variable
                                Nodo nodoDer = obtenerSubArbol(raiz.derecho);

                                raiz.izquierdo.izquierdo.padre = raiz;
                                raiz.derecho = raiz.izquierdo.izquierdo;

                                raiz.izquierdo.izquierdo = nodoDer;
                                nodoDer.padre = raiz.izquierdo;
                                detectaConmutacion = true;
                            }

                        }else if(raiz.izquierdo.derecho.token.kind == NEGACION && !detectaConmutacion){//Verifica que el nodo DERECHO de la conjunción hija sea una negación

                            if(raiz.derecho.token.image.equals(raiz.izquierdo.derecho.derecho.token.image)){//Verifica que sean la misma variable
                                Nodo nodoDer = obtenerSubArbol(raiz.derecho);

                                raiz.izquierdo.izquierdo.padre = raiz;
                                raiz.derecho = raiz.izquierdo.izquierdo;

                                raiz.izquierdo.izquierdo = nodoDer;
                                nodoDer.padre = raiz.izquierdo;
                                detectaConmutacion = true;
                            }
                        }

                    }else if(raiz.derecho.token.kind == NEGACION){//Verifica que de lado derecho haya una negación (seguida de una variable)
                        //Se trata el nodo izquierdo.izquierdo
                        if(raiz.izquierdo.izquierdo.token.kind == VARIABLE && !detectaConmutacion){//Verifica que el nodo IZQUIERDO de la conjunción hija sea una variable

                            if(raiz.derecho.derecho.token.image.equals(raiz.izquierdo.izquierdo.token.image)){//Verifica que sean la misma variable
                                Nodo nodoDer = obtenerSubArbol(raiz.derecho);

                                raiz.izquierdo.derecho.padre = raiz;
                                raiz.derecho = raiz.izquierdo.derecho;

                                raiz.izquierdo.derecho = nodoDer;
                                nodoDer.padre = raiz.izquierdo;
                                detectaConmutacion = true;
                            }

                        }else if(raiz.izquierdo.izquierdo.token.kind == NEGACION && !detectaConmutacion){//Verifica que el nodo IZQUIERDO de la conjunción hija sea una negación

                            if(raiz.derecho.derecho.token.image.equals(raiz.izquierdo.izquierdo.derecho.token.image)){//Verifica que sean la misma variable
                                Nodo nodoDer = obtenerSubArbol(raiz.derecho);

                                raiz.izquierdo.derecho.padre = raiz;
                                raiz.derecho = raiz.izquierdo.derecho;

                                raiz.izquierdo.derecho = nodoDer;
                                nodoDer.padre = raiz.izquierdo;
                                detectaConmutacion = true;
                            }

                        }

                        //Se trata el nodo izquierdo.derecho
                        if(raiz.izquierdo.derecho.token.kind == VARIABLE && !detectaConmutacion){//Verifica que el nodo DERECHO de la conjunción hija sea una variable

                            if(raiz.derecho.derecho.token.image.equals(raiz.izquierdo.derecho.token.image)){//Verifica que sean la misma variable
                                Nodo nodoDer = obtenerSubArbol(raiz.derecho);

                                raiz.izquierdo.izquierdo.padre = raiz;
                                raiz.derecho = raiz.izquierdo.izquierdo;

                                raiz.izquierdo.izquierdo = nodoDer;
                                nodoDer.padre = raiz.izquierdo;
                                detectaConmutacion = true;
                            }

                        }else if(raiz.izquierdo.derecho.token.kind == NEGACION && !detectaConmutacion){//Verifica que el nodo DERECHO de la conjunción hija sea una negación

                            if(raiz.derecho.derecho.token.image.equals(raiz.izquierdo.derecho.derecho.token.image)){//Verifica que sean la misma variable
                                Nodo nodoDer = obtenerSubArbol(raiz.derecho);

                                raiz.izquierdo.izquierdo.padre = raiz;
                                raiz.derecho = raiz.izquierdo.izquierdo;

                                raiz.izquierdo.izquierdo = nodoDer;
                                nodoDer.padre = raiz.izquierdo;
                                detectaConmutacion = true;
                            }
                        }
                    }
                }//Fin conjunción a la IZQUIERDA

                //Verifica que la otra conjunción esté a la DERECHA
                if(raiz.derecho.token.kind == CONJUNCION){

                    if(raiz.izquierdo.token.kind == VARIABLE){ //Verifica de lado IZQUIERDO haya una variable (sola)

                        //Se trata que el Nodo raiz.izquierdo == raiz.derecho.izquierdo
                        if(raiz.derecho.izquierdo.token.kind == VARIABLE && !detectaConmutacion){//Verifica que el nodo IZQUIERDO de la conjunción hija sea una variable

                            if(raiz.izquierdo.token.image.equals(raiz.derecho.izquierdo.token.image)){//Verifica que sean la misma variable
                                Nodo nodoIzq = obtenerSubArbol(raiz.izquierdo);

                                raiz.derecho.derecho.padre = raiz;
                                raiz.izquierdo = raiz.derecho.derecho;

                                raiz.derecho.derecho = nodoIzq;
                                nodoIzq.padre = raiz.derecho;
                                detectaConmutacion = true;
                            }

                        }else if(raiz.derecho.izquierdo.token.kind == NEGACION && !detectaConmutacion){//Verifica que el nodo IZQUIERDO de la conjunción hija sea una negación

                            if(raiz.izquierdo.token.image.equals(raiz.derecho.izquierdo.derecho.token.image)){//Verifica que sean la misma variable
                                Nodo nodoIzq = obtenerSubArbol(raiz.izquierdo);

                                raiz.derecho.derecho.padre = raiz;
                                raiz.izquierdo = raiz.derecho.derecho;

                                raiz.derecho.derecho = nodoIzq;
                                nodoIzq.padre = raiz.derecho;
                                detectaConmutacion = true;
                            }
                        }

                        //Se trata que el Nodo raiz.izquierdo == raiz.derecho.derecho
                        if(raiz.derecho.derecho.token.kind == VARIABLE && !detectaConmutacion){//Verifica que el nodo DERECHO de la conjunción hija sea una variable

                            if(raiz.izquierdo.token.image.equals(raiz.derecho.derecho.token.image)){//Verifica que sean la misma variable
                                Nodo nodoIzq = obtenerSubArbol(raiz.izquierdo);

                                raiz.derecho.izquierdo.padre = raiz;
                                raiz.izquierdo = raiz.derecho.izquierdo;

                                raiz.derecho.izquierdo = nodoIzq;
                                nodoIzq.padre = raiz.derecho;
                                detectaConmutacion = true;
                            }
                        }else if(raiz.derecho.derecho.token.kind == NEGACION && !detectaConmutacion){//Verifica que el nodo DERECHO de la conjunción hija sea una negación

                            if(raiz.izquierdo.token.image.equals(raiz.derecho.derecho.derecho.token.image)){//Verifica que sean la misma variable
                                Nodo nodoIzq = obtenerSubArbol(raiz.izquierdo);

                                raiz.derecho.izquierdo.padre = raiz;
                                raiz.izquierdo = raiz.derecho.izquierdo;

                                raiz.derecho.izquierdo = nodoIzq;
                                nodoIzq.padre = raiz.derecho;
                                detectaConmutacion = true;
                            }
                        }


                    }else if(raiz.izquierdo.token.kind == NEGACION){//Verifica que de lado IZQUIERDO haya una negación (seguida de una variable)

                        //Se trata que el Nodo raiz.izquierdo == raiz.derecho.izquierdo
                        if(raiz.derecho.izquierdo.token.kind == VARIABLE && !detectaConmutacion){//Verifica que el nodo IZQUIERDO de la conjunción hija sea una variable

                            if(raiz.izquierdo.derecho.token.image.equals(raiz.derecho.izquierdo.token.image)){//Verifica que sean la misma variable
                                Nodo nodoIzq = obtenerSubArbol(raiz.izquierdo);

                                raiz.derecho.derecho.padre = raiz;
                                raiz.izquierdo = raiz.derecho.derecho;

                                raiz.derecho.derecho = nodoIzq;
                                nodoIzq.padre = raiz.derecho;
                                detectaConmutacion = true;
                            }

                        }else if(raiz.derecho.izquierdo.token.kind == NEGACION && !detectaConmutacion){//Verifica que el nodo IZQUIERDO de la disyunción hija sea una negación

                            if(raiz.izquierdo.derecho.token.image.equals(raiz.derecho.izquierdo.derecho.token.image)){//Verifica que sean la misma variable
                                Nodo nodoIzq = obtenerSubArbol(raiz.izquierdo);

                                raiz.derecho.derecho.padre = raiz;
                                raiz.izquierdo = raiz.derecho.derecho;

                                raiz.derecho.derecho = nodoIzq;
                                nodoIzq.padre = raiz.derecho;
                                detectaConmutacion = true;
                            }
                        }

                        //Se trata que el Nodo raiz.izquierdo == raiz.derecho.derecho
                        if(raiz.derecho.derecho.token.kind == VARIABLE && !detectaConmutacion){//Verifica que el nodo DERECHO de la conjunción hija sea una variable

                            if(raiz.izquierdo.derecho.token.image.equals(raiz.derecho.derecho.token.image)){//Verifica que sean la misma variable
                                Nodo nodoIzq = obtenerSubArbol(raiz.izquierdo);

                                raiz.derecho.izquierdo.padre = raiz;
                                raiz.izquierdo = raiz.derecho.izquierdo;

                                raiz.derecho.izquierdo = nodoIzq;
                                nodoIzq.padre = raiz.derecho;
                                detectaConmutacion = true;
                            }
                        }else if(raiz.derecho.derecho.token.kind == NEGACION && !detectaConmutacion){//Verifica que el nodo DERECHO de la conjunción hija sea una negación

                            if(raiz.izquierdo.derecho.token.image.equals(raiz.derecho.derecho.derecho.token.image)){//Verifica que sean la misma variable
                                Nodo nodoIzq = obtenerSubArbol(raiz.izquierdo);

                                raiz.derecho.izquierdo.padre = raiz;
                                raiz.izquierdo = raiz.derecho.izquierdo;

                                raiz.derecho.izquierdo = nodoIzq;
                                nodoIzq.padre = raiz.derecho;
                                detectaConmutacion = true;
                            }
                        }
                    }
                }//Fin conjunción a la derecha
            }//Fin conmutación de la conjunción

        }

        void idempotencia(Nodo raiz){
            if(raiz.token.kind == CONJUNCION || raiz.token.kind == DISYUNCION){

                if(raiz.izquierdo.token.kind == VARIABLE){

                    if(raiz.izquierdo.token.image.equals(raiz.derecho.token.image)){//Comprueba que ambos nodos sean variable e iguales
                        Nodo nodoRaiz = obtenerSubArbol(raiz.izquierdo);

                        if(raiz.padre != null){
                            if(raiz.padre.izquierdo == raiz){//el nodo está a la izquierda del padre
                                raiz.padre.izquierdo = nodoRaiz;
                                nodoRaiz.padre = raiz.padre;

                            }else if(raiz.padre.derecho == raiz){//el nodo está a la derecha del padre
                                raiz.padre.derecho = nodoRaiz;
                                nodoRaiz.padre = raiz.padre;
                            }
                        }else{//el nodo es la raiz del arbol
                            this.arbol.raiz = nodoRaiz;
                            nodoRaiz.padre = null;
                        }
                    }


                }else if(raiz.izquierdo.token.kind == NEGACION){

                    if(raiz.derecho.token.kind == NEGACION){

                        if(raiz.izquierdo.derecho.token.image.equals(raiz.derecho.derecho.token.image)){//Comprueba que ambos nodos sean variable e iguales
                            Nodo nodoRaiz = obtenerSubArbol(raiz.izquierdo);

                            if(raiz.padre != null){
                                if(raiz.padre.izquierdo == raiz){//el nodo está a la izquierda del padre
                                    raiz.padre.izquierdo = nodoRaiz;
                                    nodoRaiz.padre = raiz.padre;

                                }else if(raiz.padre.derecho == raiz){//el nodo está a la derecha del padre
                                    raiz.padre.derecho = nodoRaiz;
                                    nodoRaiz.padre = raiz.padre;
                                }
                            }else{//el nodo es la raiz del arbol
                                this.arbol.raiz = nodoRaiz;
                                nodoRaiz.padre = null;
                            }
                        }
                    }

                }

            }
        }

        void complementacion(Nodo raiz){

            if(raiz.token.kind == DISYUNCION){

                if(raiz.izquierdo.token.kind == VARIABLE && raiz.derecho.token.kind == NEGACION){
                    //Comprueba que haya una variable del lado izquierdo y de lado derecho una negacion 
                    if(raiz.izquierdo.token.image.equals(raiz.derecho.derecho.token.image)){
                        Nodo nodoRaiz = new Nodo(new Token(TAUTOLOGIA,"1"));

                        if(raiz.padre != null){
                            if(raiz.padre.izquierdo == raiz){//el nodo está a la izquierda del padre
                                raiz.padre.izquierdo = nodoRaiz;
                                nodoRaiz.padre = raiz.padre;

                            }else if(raiz.padre.derecho == raiz){//el nodo está a la derecha del padre
                                raiz.padre.derecho = nodoRaiz;
                                nodoRaiz.padre = raiz.padre;
                            }
                        }else{//el nodo es la raiz del arbol
                            this.arbol.raiz = nodoRaiz;
                            nodoRaiz.padre = null;
                        }
                    }

                }else if(raiz.izquierdo.token.kind == NEGACION && raiz.derecho.token.kind == VARIABLE){
                    //Comprueba que haya una negación de lado izquierdo y una variable de lado derecho
                    if(raiz.izquierdo.derecho.token.image.equals(raiz.derecho.token.image)){
                        Nodo nodoRaiz = new Nodo(new Token(TAUTOLOGIA,"1"));

                        if(raiz.padre != null){
                            if(raiz.padre.izquierdo == raiz){//el nodo está a la izquierda del padre
                                raiz.padre.izquierdo = nodoRaiz;
                                nodoRaiz.padre = raiz.padre;

                            }else if(raiz.padre.derecho == raiz){//el nodo está a la derecha del padre
                                raiz.padre.derecho = nodoRaiz;
                                nodoRaiz.padre = raiz.padre;
                            }
                        }else{//el nodo es la raiz del arbol
                            this.arbol.raiz = nodoRaiz;
                            nodoRaiz.padre = null;
                        }
                    }
                }

            }else if(raiz.token.kind == CONJUNCION){

                if(raiz.izquierdo.token.kind == VARIABLE && raiz.derecho.token.kind == NEGACION){
                    //Comprueba que haya una variable del lado izquierdo y de lado derecho una negacion 
                    if(raiz.izquierdo.token.image.equals(raiz.derecho.derecho.token.image)){
                        Nodo nodoRaiz = new Nodo(new Token(CONTRADICCION,"0"));

                        if(raiz.padre != null){
                            if(raiz.padre.izquierdo == raiz){//el nodo está a la izquierda del padre
                                raiz.padre.izquierdo = nodoRaiz;
                                nodoRaiz.padre = raiz.padre;

                            }else if(raiz.padre.derecho == raiz){//el nodo está a la derecha del padre
                                raiz.padre.derecho = nodoRaiz;
                                nodoRaiz.padre = raiz.padre;
                            }
                        }else{//el nodo es la raiz del arbol
                            this.arbol.raiz = nodoRaiz;
                            nodoRaiz.padre = null;
                        }
                    }

                }else if(raiz.izquierdo.token.kind == NEGACION && raiz.derecho.token.kind == VARIABLE){
                    //Comprueba que haya una negación de lado izquierdo y una variable de lado derecho
                    if(raiz.izquierdo.derecho.token.image.equals(raiz.derecho.token.image)){
                        Nodo nodoRaiz = new Nodo(new Token(CONTRADICCION,"0"));

                        if(raiz.padre != null){
                            if(raiz.padre.izquierdo == raiz){//el nodo está a la izquierda del padre
                                raiz.padre.izquierdo = nodoRaiz;
                                nodoRaiz.padre = raiz.padre;

                            }else if(raiz.padre.derecho == raiz){//el nodo está a la derecha del padre
                                raiz.padre.derecho = nodoRaiz;
                                nodoRaiz.padre = raiz.padre;
                            }
                        }else{//el nodo es la raiz del arbol
                            this.arbol.raiz = nodoRaiz;
                            nodoRaiz.padre = null;
                        }
                    }
                }
            }


        }
    }

  final public void inicializarArbol() throws ParseException {
    Arbol arbol;
    ConversionFNC conversion;
    arbol = condicionales();
                            System.out.println("Fin"); arbol.enOrden(); conversion = new ConversionFNC(arbol); conversion.generarFNC(); arbol.enOrden();
  }

  final public Arbol condicionales() throws ParseException {
    Arbol arbolIzq, arbolDer;
    Token t;
    arbolIzq = operacionesLogicas();
    label_1:
    while (true) {
      if (jj_2_1(2)) {
        ;
      } else {
        break label_1;
      }
      if (jj_2_2(2)) {
        jj_consume_token(CONDICIONAL);
                          t = token;
        arbolDer = operacionesLogicas();
                                                                        arbolIzq.insertar(arbolIzq, arbolDer, new Nodo(t));
      } else if (jj_2_3(2)) {
        jj_consume_token(BICONDICIONAL);
                          t = token;
        arbolDer = operacionesLogicas();
                                                                        arbolIzq.insertar(arbolIzq, arbolDer, new Nodo(t));
      } else {
        jj_consume_token(-1);
        throw new ParseException();
      }
    }
         {if (true) return arbolIzq;}
    throw new Error("Missing return statement in function");
  }

  final public Arbol operacionesLogicas() throws ParseException {
    Arbol arbolIzq, arbolDer;
    Token t;
    arbolIzq = procesarNegacion();
    label_2:
    while (true) {
      if (jj_2_4(2)) {
        ;
      } else {
        break label_2;
      }
      if (jj_2_5(2)) {
        jj_consume_token(CONJUNCION);
                       t = token;
        arbolDer = procesarNegacion();
                                                                   arbolIzq.insertar(arbolIzq, arbolDer, new Nodo(t));
      } else if (jj_2_6(2)) {
        jj_consume_token(DISYUNCION);
                       t = token;
        arbolDer = procesarNegacion();
                                                                   arbolIzq.insertar(arbolIzq, arbolDer, new Nodo(t));
      } else {
        jj_consume_token(-1);
        throw new ParseException();
      }
    }
         {if (true) return arbolIzq;}
    throw new Error("Missing return statement in function");
  }

  final public Arbol procesarNegacion() throws ParseException {
    Arbol arbolIzq = new Arbol(); //ArbolIzq tiene todas las negaciones
    Arbol arbolDer;
    if (jj_2_7(2)) {
      jj_consume_token(NEGACION);
        if(arbolIzq.raiz == null){//Crea el nodo de negacion y busca cual es el ultimo hacia la derecha
            arbolIzq.setRaiz(new Nodo(token));
        }else{
            Nodo actual = arbolIzq.raiz;
            while(actual.derecho != null){
                actual = actual.derecho;
            }
            actual.derecho = new Nodo(token);
            actual.derecho.padre = actual; //SE DICE QUIEN ES EL NODO PADRE
        }
      arbolDer = procesarNegacion();
    } else if (jj_2_8(2)) {
      arbolDer = procesarVariable();
    } else {
      jj_consume_token(-1);
      throw new ParseException();
    }
        if(arbolIzq.raiz == null){
            arbolIzq.setRaiz(arbolDer.raiz);
        }
        else{
            Nodo actual = arbolIzq.raiz; //Se obtiene el nodo del arbol
            while(actual.derecho != null){
                actual = actual.derecho; //Se recorre hasta el ultimo nodo a la derecha en caso de haya habido negaciones
            }

            actual.derecho = arbolDer.raiz;
            arbolDer.raiz.padre = actual;//SE DICE QUIEN ES EL NODO PADRE
        }
        {if (true) return arbolIzq;}
    throw new Error("Missing return statement in function");
  }

  final public Arbol procesarVariable() throws ParseException {
    Arbol arbol;
    if (jj_2_9(2)) {
      jj_consume_token(VARIABLE);
                 arbol = new Arbol(new Nodo(token));
    } else if (jj_2_10(2)) {
      arbol = procesarAgrupaciones();
    } else {
      jj_consume_token(-1);
      throw new ParseException();
    }
                                                                                          {if (true) return arbol;}
    throw new Error("Missing return statement in function");
  }

  final public Arbol procesarAgrupaciones() throws ParseException {
    Arbol arbol;
    if (jj_2_11(2)) {
      jj_consume_token(PARENTESIS_IZQ);
      arbol = condicionales();
      jj_consume_token(PARENTESIS_DER);
                                                                 {if (true) return arbol;}
    } else if (jj_2_12(2)) {
      jj_consume_token(CORCHETE_IZQ);
      arbol = condicionales();
      jj_consume_token(CORCHETE_DER);
                                                               {if (true) return arbol;}
    } else if (jj_2_13(2)) {
      jj_consume_token(LLAVE_IZQ);
      arbol = condicionales();
      jj_consume_token(LLAVE_DER);
                                                            {if (true) return arbol;}
    } else {
      jj_consume_token(-1);
      throw new ParseException();
    }
    throw new Error("Missing return statement in function");
  }

  private boolean jj_2_1(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_1(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(0, xla); }
  }

  private boolean jj_2_2(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_2(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(1, xla); }
  }

  private boolean jj_2_3(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_3(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(2, xla); }
  }

  private boolean jj_2_4(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_4(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(3, xla); }
  }

  private boolean jj_2_5(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_5(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(4, xla); }
  }

  private boolean jj_2_6(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_6(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(5, xla); }
  }

  private boolean jj_2_7(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_7(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(6, xla); }
  }

  private boolean jj_2_8(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_8(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(7, xla); }
  }

  private boolean jj_2_9(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_9(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(8, xla); }
  }

  private boolean jj_2_10(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_10(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(9, xla); }
  }

  private boolean jj_2_11(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_11(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(10, xla); }
  }

  private boolean jj_2_12(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_12(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(11, xla); }
  }

  private boolean jj_2_13(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_13(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(12, xla); }
  }

  private boolean jj_3_7() {
    if (jj_scan_token(NEGACION)) return true;
    if (jj_3R_4()) return true;
    return false;
  }

  private boolean jj_3R_4() {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3_7()) {
    jj_scanpos = xsp;
    if (jj_3_8()) return true;
    }
    return false;
  }

  private boolean jj_3_6() {
    if (jj_scan_token(DISYUNCION)) return true;
    if (jj_3R_4()) return true;
    return false;
  }

  private boolean jj_3_5() {
    if (jj_scan_token(CONJUNCION)) return true;
    if (jj_3R_4()) return true;
    return false;
  }

  private boolean jj_3_4() {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3_5()) {
    jj_scanpos = xsp;
    if (jj_3_6()) return true;
    }
    return false;
  }

  private boolean jj_3_13() {
    if (jj_scan_token(LLAVE_IZQ)) return true;
    if (jj_3R_7()) return true;
    return false;
  }

  private boolean jj_3_12() {
    if (jj_scan_token(CORCHETE_IZQ)) return true;
    if (jj_3R_7()) return true;
    return false;
  }

  private boolean jj_3_11() {
    if (jj_scan_token(PARENTESIS_IZQ)) return true;
    if (jj_3R_7()) return true;
    return false;
  }

  private boolean jj_3R_6() {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3_11()) {
    jj_scanpos = xsp;
    if (jj_3_12()) {
    jj_scanpos = xsp;
    if (jj_3_13()) return true;
    }
    }
    return false;
  }

  private boolean jj_3_10() {
    if (jj_3R_6()) return true;
    return false;
  }

  private boolean jj_3R_3() {
    if (jj_3R_4()) return true;
    return false;
  }

  private boolean jj_3_3() {
    if (jj_scan_token(BICONDICIONAL)) return true;
    if (jj_3R_3()) return true;
    return false;
  }

  private boolean jj_3_9() {
    if (jj_scan_token(VARIABLE)) return true;
    return false;
  }

  private boolean jj_3_2() {
    if (jj_scan_token(CONDICIONAL)) return true;
    if (jj_3R_3()) return true;
    return false;
  }

  private boolean jj_3_1() {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3_2()) {
    jj_scanpos = xsp;
    if (jj_3_3()) return true;
    }
    return false;
  }

  private boolean jj_3R_5() {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3_9()) {
    jj_scanpos = xsp;
    if (jj_3_10()) return true;
    }
    return false;
  }

  private boolean jj_3R_7() {
    if (jj_3R_3()) return true;
    return false;
  }

  private boolean jj_3_8() {
    if (jj_3R_5()) return true;
    return false;
  }

  /** Generated Token Manager. */
  public AnalizadorTokenManager token_source;
  SimpleCharStream jj_input_stream;
  /** Current token. */
  public Token token;
  /** Next token. */
  public Token jj_nt;
  private int jj_ntk;
  private Token jj_scanpos, jj_lastpos;
  private int jj_la;
  /** Whether we are looking ahead. */
  private boolean jj_lookingAhead = false;
  private boolean jj_semLA;
  private int jj_gen;
  final private int[] jj_la1 = new int[0];
  static private int[] jj_la1_0;
  static {
      jj_la1_init_0();
   }
   private static void jj_la1_init_0() {
      jj_la1_0 = new int[] {};
   }
  final private JJCalls[] jj_2_rtns = new JJCalls[13];
  private boolean jj_rescan = false;
  private int jj_gc = 0;

  /** Constructor with InputStream. */
  public Analizador(java.io.InputStream stream) {
     this(stream, null);
  }
  /** Constructor with InputStream and supplied encoding */
  public Analizador(java.io.InputStream stream, String encoding) {
    try { jj_input_stream = new SimpleCharStream(stream, encoding, 1, 1); } catch(java.io.UnsupportedEncodingException e) { throw new RuntimeException(e); }
    token_source = new AnalizadorTokenManager(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 0; i++) jj_la1[i] = -1;
    for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  /** Reinitialise. */
  public void ReInit(java.io.InputStream stream) {
     ReInit(stream, null);
  }
  /** Reinitialise. */
  public void ReInit(java.io.InputStream stream, String encoding) {
    try { jj_input_stream.ReInit(stream, encoding, 1, 1); } catch(java.io.UnsupportedEncodingException e) { throw new RuntimeException(e); }
    token_source.ReInit(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 0; i++) jj_la1[i] = -1;
    for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  /** Constructor. */
  public Analizador(java.io.Reader stream) {
    jj_input_stream = new SimpleCharStream(stream, 1, 1);
    token_source = new AnalizadorTokenManager(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 0; i++) jj_la1[i] = -1;
    for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  /** Reinitialise. */
  public void ReInit(java.io.Reader stream) {
    jj_input_stream.ReInit(stream, 1, 1);
    token_source.ReInit(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 0; i++) jj_la1[i] = -1;
    for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  /** Constructor with generated Token Manager. */
  public Analizador(AnalizadorTokenManager tm) {
    token_source = tm;
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 0; i++) jj_la1[i] = -1;
    for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  /** Reinitialise. */
  public void ReInit(AnalizadorTokenManager tm) {
    token_source = tm;
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 0; i++) jj_la1[i] = -1;
    for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  private Token jj_consume_token(int kind) throws ParseException {
    Token oldToken;
    if ((oldToken = token).next != null) token = token.next;
    else token = token.next = token_source.getNextToken();
    jj_ntk = -1;
    if (token.kind == kind) {
      jj_gen++;
      if (++jj_gc > 100) {
        jj_gc = 0;
        for (int i = 0; i < jj_2_rtns.length; i++) {
          JJCalls c = jj_2_rtns[i];
          while (c != null) {
            if (c.gen < jj_gen) c.first = null;
            c = c.next;
          }
        }
      }
      return token;
    }
    token = oldToken;
    jj_kind = kind;
    throw generateParseException();
  }

  static private final class LookaheadSuccess extends java.lang.Error { }
  final private LookaheadSuccess jj_ls = new LookaheadSuccess();
  private boolean jj_scan_token(int kind) {
    if (jj_scanpos == jj_lastpos) {
      jj_la--;
      if (jj_scanpos.next == null) {
        jj_lastpos = jj_scanpos = jj_scanpos.next = token_source.getNextToken();
      } else {
        jj_lastpos = jj_scanpos = jj_scanpos.next;
      }
    } else {
      jj_scanpos = jj_scanpos.next;
    }
    if (jj_rescan) {
      int i = 0; Token tok = token;
      while (tok != null && tok != jj_scanpos) { i++; tok = tok.next; }
      if (tok != null) jj_add_error_token(kind, i);
    }
    if (jj_scanpos.kind != kind) return true;
    if (jj_la == 0 && jj_scanpos == jj_lastpos) throw jj_ls;
    return false;
  }


/** Get the next Token. */
  final public Token getNextToken() {
    if (token.next != null) token = token.next;
    else token = token.next = token_source.getNextToken();
    jj_ntk = -1;
    jj_gen++;
    return token;
  }

/** Get the specific Token. */
  final public Token getToken(int index) {
    Token t = jj_lookingAhead ? jj_scanpos : token;
    for (int i = 0; i < index; i++) {
      if (t.next != null) t = t.next;
      else t = t.next = token_source.getNextToken();
    }
    return t;
  }

  private int jj_ntk() {
    if ((jj_nt=token.next) == null)
      return (jj_ntk = (token.next=token_source.getNextToken()).kind);
    else
      return (jj_ntk = jj_nt.kind);
  }

  private java.util.List jj_expentries = new java.util.ArrayList();
  private int[] jj_expentry;
  private int jj_kind = -1;
  private int[] jj_lasttokens = new int[100];
  private int jj_endpos;

  private void jj_add_error_token(int kind, int pos) {
    if (pos >= 100) return;
    if (pos == jj_endpos + 1) {
      jj_lasttokens[jj_endpos++] = kind;
    } else if (jj_endpos != 0) {
      jj_expentry = new int[jj_endpos];
      for (int i = 0; i < jj_endpos; i++) {
        jj_expentry[i] = jj_lasttokens[i];
      }
      boolean exists = false;
      for (java.util.Iterator it = jj_expentries.iterator(); it.hasNext();) {
        int[] oldentry = (int[])(it.next());
        if (oldentry.length == jj_expentry.length) {
          exists = true;
          for (int i = 0; i < jj_expentry.length; i++) {
            if (oldentry[i] != jj_expentry[i]) {
              exists = false;
              break;
            }
          }
          if (exists) break;
        }
      }
      if (!exists) jj_expentries.add(jj_expentry);
      if (pos != 0) jj_lasttokens[(jj_endpos = pos) - 1] = kind;
    }
  }

  /** Generate ParseException. */
  public ParseException generateParseException() {
    jj_expentries.clear();
    boolean[] la1tokens = new boolean[20];
    if (jj_kind >= 0) {
      la1tokens[jj_kind] = true;
      jj_kind = -1;
    }
    for (int i = 0; i < 0; i++) {
      if (jj_la1[i] == jj_gen) {
        for (int j = 0; j < 32; j++) {
          if ((jj_la1_0[i] & (1<<j)) != 0) {
            la1tokens[j] = true;
          }
        }
      }
    }
    for (int i = 0; i < 20; i++) {
      if (la1tokens[i]) {
        jj_expentry = new int[1];
        jj_expentry[0] = i;
        jj_expentries.add(jj_expentry);
      }
    }
    jj_endpos = 0;
    jj_rescan_token();
    jj_add_error_token(0, 0);
    int[][] exptokseq = new int[jj_expentries.size()][];
    for (int i = 0; i < jj_expentries.size(); i++) {
      exptokseq[i] = (int[])jj_expentries.get(i);
    }
    return new ParseException(token, exptokseq, tokenImage);
  }

  /** Enable tracing. */
  final public void enable_tracing() {
  }

  /** Disable tracing. */
  final public void disable_tracing() {
  }

  private void jj_rescan_token() {
    jj_rescan = true;
    for (int i = 0; i < 13; i++) {
    try {
      JJCalls p = jj_2_rtns[i];
      do {
        if (p.gen > jj_gen) {
          jj_la = p.arg; jj_lastpos = jj_scanpos = p.first;
          switch (i) {
            case 0: jj_3_1(); break;
            case 1: jj_3_2(); break;
            case 2: jj_3_3(); break;
            case 3: jj_3_4(); break;
            case 4: jj_3_5(); break;
            case 5: jj_3_6(); break;
            case 6: jj_3_7(); break;
            case 7: jj_3_8(); break;
            case 8: jj_3_9(); break;
            case 9: jj_3_10(); break;
            case 10: jj_3_11(); break;
            case 11: jj_3_12(); break;
            case 12: jj_3_13(); break;
          }
        }
        p = p.next;
      } while (p != null);
      } catch(LookaheadSuccess ls) { }
    }
    jj_rescan = false;
  }

  private void jj_save(int index, int xla) {
    JJCalls p = jj_2_rtns[index];
    while (p.gen > jj_gen) {
      if (p.next == null) { p = p.next = new JJCalls(); break; }
      p = p.next;
    }
    p.gen = jj_gen + xla - jj_la; p.first = token; p.arg = xla;
  }

  static final class JJCalls {
    int gen;
    Token first;
    int arg;
    JJCalls next;
  }

}
